stages:
  - build
  - test

before_script:
  - curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
  - apt-get update -qqy
  - apt-get install -qqy nodejs
  - npm install -g yarn

build:
  stage: build
  script:
    - yarn install  
    - yarn build

test:
  stage: test
  script:
    - yarn install  
    - yarn test
